### ISSUE TITLE
Incorrect boot.img/magisk_patched.img Version Numbers For Nothing Phone (1) Boot Images?

### ISSUE THREAD

**Issue by SkeleBones** [reindex-ot/reindex-ot.github.io#1]
I recently got a Nothing Phone (1) and used your patched images to root it. My current OS version is 1.5.4 according to the device's settings, but the only images that allowed my phone to boot were the 1.5.5 ones. So, I am confused if these numbers are incorrect or if my OS version isn't what it claims to be. I recently went to update it to 1.5.5, but it would not allow me to even after re-patching the stock 1.5.5 boot.img from your site. I may just be dumb because I am not well versed in this whole thing.

**Comment by reindex-ot** [comment]
You can either use an unpatched one and patch it yourself, or use the boot.img in the Fastboot ROM.

**Comment by SkeleBones** [comment]
That worked. Thank you.
