### ISSUE TITLE
Some more check to Nothing Phone 1 (and maybe others) flash script

### ISSUE THREAD

**Issue by falcon4fun** [reindex-ot/reindex-ot.github.io#2]
I would suggest you to add some more fail-fool checks to flash script:

1. Check if flashing unlock and flashing critical_unlock should return unlocked. Else stop script.
2. Check if set_active command doesn't return any error. Else stop script.

Case:
- If flashing unlocked and flashing critical not, phone will bootloop because not all partition could be flashed
- If set_active command return error "Unrecognized command", this means phone is inside fastboot instead of bootloader.
You will hardbrick to QUSB mode (EDL) with black screen after flashing via fastboot. Got this situation yesterday. Flashed with wrong mode.
XDA shows not only me has the same case (next message to my):
https://xdaforums.com/t/unbrick-tool-edl-flash-read-repair-region-change-tool.4552471/page-9#post-89332254

**Comment by reindex-ot** [comment]
fastboot reboot fastboot
I'm thinking of changing it to reboot.
